#services:
#  mysql:
#    image: mysql:8.0
#    container_name: indikart-mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "3307:3306"
#    volumes:
#      - indikart_mysql_data:/var/lib/mysql
#    command: --default-authentication-plugin=mysql_native_password
#  redis:
#    image: redis:7.0
#    container_name: indikart-redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - indikart_redis_data:/data
#
#
#volumes:
#  indikart_mysql_data:
#  indikart_redis_data:
#    driver: local
services:
  mysql:
    image: mysql:8.0
    container_name: indikart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - indikart_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.0
    container_name: indikart-redis
    ports:
      - "6379:6379"
    volumes:
      - indikart_redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: indikart-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: indikart-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  indikart_mysql_data:
  indikart_redis_data: